[buildPlans.kg]                 # <kg> is your plan name
family = "Iosevka KG Terminal"  # Font menu family name
design = [
            "cv08", "cv11", "cv19", "cv43", "cv49", "cv55", "cv62", "cv92",
           #`l`,    `g`,    `*`,     `Q`,   `y`,    `$`,    `%` and `G`
            "no-ligation"
         ] # Customize styles
hintParams = ["-a", "sss"]              # Optional custom parameters for ttfautohint


# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#              and "shape" properly only supports number between 100 and 900 (inclusive)

[buildPlans.kg.weights.regular]
shape = 500  # Weight for glyph shapes
menu  = 500  # Weight for menu name
css   = 500  # Weight for webfont CSS

[buildPlans.kg.weights.bold]
shape = 700
menu  = 700
css   = 700
# end weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.kg.slants]
upright = "normal"
italic = "italic"
oblique = "italic"


##########################
#  Custom style chosen
##########################


# 100 	Thin (Hairline)
# 200 	Extra Light (Ultra Light)
# 300 	Light
# 400 	Normal (Regular)
# 500 	Medium
# 600 	Semi Bold (Demi Bold)
# 700 	Bold
# 800 	Extra Bold (Ultra Bold)
# 900 	Black (Heavy)
# 950 	Extra Black (Ultra Black)
