[buildPlans.iosevka-kg]                             # <iosevka-kg> is your plan name
family = "Iosevka KG"                               # Font menu family name
design = ["cv10", "cv19", "cv24", "cv46", "cv51", "cv65", "cv92"] # Customize styles
hintParams = ["-a", "sss"]                          # Optional custom parameters for ttfautohint


# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#              and "shape" properly only supports number between 100 and 900 (inclusive)

[buildPlans.iosevka-kg.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS

[buildPlans.iosevka-kg.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-kg.weights.bold]
shape = 700
menu  = 700
css   = 700
# end weight section

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-kg.slants]
upright = "normal"
italic = "italic"
#oblique = "oblique"


##########################
#  Custom style chosen
##########################

# Iosevka Term
# Medium Extended
# "cv10", "cv16", "cv19", "cv24", "cv46", "cv51", "cv65", "cv92"
# calt - ligatures


# 100 	Thin (Hairline)
# 200 	Extra Light (Ultra Light)
# 300 	Light
# 400 	Normal (Regular)
# 500 	Medium
# 600 	Semi Bold (Demi Bold)
# 700 	Bold
# 800 	Extra Bold (Ultra Bold)
# 900 	Black (Heavy)
# 950 	Extra Black (Ultra Black)
